const buildingIcons: Record<number, number> = {
  // Let the townhall commented
  // 1000001: require("@/assets/images/clash/buildings/town-hall.png"),
  
  1000000: require("@/assets/images/clash/buildings/army-camp.png"),
  1000002: require("@/assets/images/clash/buildings/elixir-collector.png"),
  1000003: require("@/assets/images/clash/buildings/elixir-storage.png"),
  1000004: require("@/assets/images/clash/buildings/gold-mine.png"),
  1000005: require("@/assets/images/clash/buildings/gold-storage.png"),
  1000006: require("@/assets/images/clash/buildings/barracks.png"),
  1000007: require("@/assets/images/clash/buildings/laboratory.png"),
  1000008: require("@/assets/images/clash/buildings/cannon.png"),
  1000009: require("@/assets/images/clash/buildings/archer-tower.png"),
  1000010: require("@/assets/images/clash/buildings/wall.png"),
  1000011: require("@/assets/images/clash/buildings/wizard-tower.png"),
  1000012: require("@/assets/images/clash/buildings/air-defense.png"),
  1000013: require("@/assets/images/clash/buildings/mortar.png"),
  1000014: require("@/assets/images/clash/buildings/clan-castle.png"),
  1000015: require("@/assets/images/clash/buildings/builder-hut.png"),
  1000019: require("@/assets/images/clash/buildings/hidden-tesla.png"),
  1000020: require("@/assets/images/clash/buildings/spell-factory.png"),
  1000021: require("@/assets/images/clash/buildings/x-bow.png"),
  1000023: require("@/assets/images/clash/buildings/dark-elixir-drill.png"),
  1000024: require("@/assets/images/clash/buildings/dark-elixir-storage.png"),
  1000026: require("@/assets/images/clash/buildings/dark-barracks.png"),
  1000027: require("@/assets/images/clash/buildings/inferno-tower.png"),
  1000028: require("@/assets/images/clash/buildings/air-sweeper.png"),
  1000029: require("@/assets/images/clash/buildings/dark-spell-factory.png"),
  1000031: require("@/assets/images/clash/buildings/eagle-artillery.png"),
  1000032: require("@/assets/images/clash/buildings/bomb-tower.png"),

  1000059: require("@/assets/images/clash/buildings/workshop.png"),
  1000064: require("@/assets/images/clash/buildings/bob-hut.png"),
  1000067: require("@/assets/images/clash/buildings/scattershot.png"),
  1000068: require("@/assets/images/clash/buildings/pet-house.png"),
  1000070: require("@/assets/images/clash/buildings/blacksmith.png"),
  1000071: require("@/assets/images/clash/buildings/hero-hall.png"),
  1000072: require("@/assets/images/clash/buildings/spell-tower.png"),
  1000077: require("@/assets/images/clash/buildings/monolith.png"),
  1000079: require("@/assets/images/clash/buildings/multi-gear-tower.png"),
  1000084: require("@/assets/images/clash/buildings/multi-archer-tower.png"),
  1000085: require("@/assets/images/clash/buildings/ricochet-cannon.png"),
  1000086: require("@/assets/images/clash/buildings/revenge-tower.png"),
  1000089: require("@/assets/images/clash/buildings/firespitter.png"),
  1000093: require("@/assets/images/clash/buildings/helper-hut.png"),
  1000097: require("@/assets/images/clash/buildings/crafted-defense.png"),
  1000102: require("@/assets/images/clash/buildings/super-wizard-tower.png"),
};

export default buildingIcons;